CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY,
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(60) NOT NULL,
  RANK NUMERIC(1) NULL
);

CREATE SEQUENCE IF NOT EXISTS USERS_SEQ START WITH 0 INCREMENT BY 1;