CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY,
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(60) NOT NULL,
  RANK NUMERIC(1) NULL
);

CREATE TABLE IF NOT EXISTS INVITES (
  ID INTEGER PRIMARY KEY,
  INVITE_KEY VARCHAR(128) NOT NULL,
  USED NUMERIC(1),
  EXPIRATION TIMESTAMP NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS USERS_SEQ START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS INVITES_SEQ START WITH 0 INCREMENT BY 1;