CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY,
  USERNAME VARCHAR(30) NOT NULL UNIQUE,
  PASSWORD VARCHAR(60) NOT NULL,
  RANK NUMERIC(1) NULL
);

CREATE TABLE IF NOT EXISTS RANKS (
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS INVITES (
  ID INTEGER PRIMARY KEY,
  INVITE_KEY VARCHAR(36) NOT NULL,
  IS_VALID NUMERIC(1) NOT NULL,
  INVALID_STATUS_CODE VARCHAR(7),
  RANK_ID INTEGER NOT NULL,
  FOREIGN KEY (RANK_ID) REFERENCES RANKS(ID),
  EXPIRATION TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PERMISSIONS (
  ID INTEGER PRIMARY KEY,
  RANK_ID INTEGER NOT NULL,
  FOREIGN KEY (RANK_ID) REFERENCES RANKS(ID),
  NAME VARCHAR(30),
  STATUS NUMERIC(1) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS USERS_SEQ START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS INVITES_SEQ START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS RANKS_SEQ START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PERMISSIONS_SEQ START WITH 0 INCREMENT BY 1;